### Task 1 (Level 1): Data Cleaning and Preprocessing

##### Import Libraries

In [41]:
import pandas as pd
import numpy as np

##### Load dataset

In [49]:
df = pd.read_csv(r"C:\Users\user\OneDrive\Desktop\CodVeda Internship\Data Set For Task\3) Sentiment dataset.csv")
df.head()

,Unnamed: 0.1,Unnamed: 0,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,0,0,Enjoying a beautiful day at the park! ...,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15.0,30.0,USA,2023,1,15,12
1,1,1,Traffic was terrible this morning. ...,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5.0,10.0,Canada,2023,1,15,8
2,2,2,Just finished an amazing workout! 💪 ...,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20.0,40.0,USA,2023,1,15,15
3,3,3,Excited about the upcoming weekend getaway! ...,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8.0,15.0,UK,2023,1,15,18
4,4,4,Trying out a new recipe for dinner tonight. ...,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12.0,25.0,Australia,2023,1,15,19

##### Explore dataset

In [50]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 732 entries, 0 to 731
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0.1  732 non-null    int64
 1   Unnamed: 0    732 non-null    int64
 2   Text          732 non-null    str
 3   Sentiment     732 non-null    str
 4   Timestamp     732 non-null    str
 5   User          732 non-null    str
 6   Platform      732 non-null    str
 7   Hashtags      732 non-null    str
 8   Retweets      732 non-null    float64
 9   Likes         732 non-null    float64
 10  Country       732 non-null    str
 11  Year          732 non-null    int64
 12  Month         732 non-null    int64
 13  Day           732 non-null    int64
 14  Hour          732 non-null    int64
dtypes: float64(2), int64(6), str(7)
memory usage: 85.9 KB

,Unnamed: 0.1,Unnamed: 0,Retweets,Likes,Year,Month,Day,Hour
count,732.000000,732.000000,732.000000,732.000000,732.000000,732.000000,732.000000,732.000000
mean,366.464481,369.740437,21.508197,42.901639,2020.471311,6.122951,15.497268,15.521858
std,211.513936,212.428936,7.061286,14.089848,2.802285,3.411763,8.474553,4.113414
min,0.000000,0.000000,5.000000,10.000000,2010.000000,1.000000,1.000000,0.000000
25%,183.750000,185.750000,17.750000,34.750000,2019.000000,3.000000,9.000000,13.000000
50%,366.500000,370.500000,22.000000,43.000000,2021.000000,6.000000,15.000000,16.000000
75%,549.250000,553.250000,25.000000,50.000000,2023.000000,9.000000,22.000000,19.000000
max,732.000000,736.000000,40.000000,80.000000,2023.000000,12.000000,31.000000,23.000000

#### Data Cleaning Process

In [51]:
# Removing Unnecessary Columns
df.drop(columns=['Unnamed: 0.1', 'Unnamed: 0'], inplace=True)

In [53]:
# Text Cleaning
df['Text'] = df['Text'].str.lower()
df['Text'] = df['Text'].str.replace(r'\.\.\.', '', regex=True)
df['Text'] = df['Text'].str.strip()

In [55]:
# Standardizing Sentiment
df['Sentiment'] = df['Sentiment'].str.strip().str.capitalize()

In [56]:
# Converting Timestamp
df['Timestamp'] = pd.to_datetime(df['Timestamp'])

In [57]:
# Data Type Conversion
df['Retweets'] = df['Retweets'].astype(int)
df['Likes'] = df['Likes'].astype(int)

In [58]:
# Checking Missing Values
df.isnull().sum()

Text         0
Sentiment    0
Timestamp    0
User         0
Platform     0
Hashtags     0
Retweets     0
Likes        0
Country      0
Year         0
Month        0
Day          0
Hour         0
dtype: int64

In [59]:
# Removing Duplicate Records
df.drop_duplicates(inplace=True)

#### Final Cleaned Dataset

In [60]:
df.info()
df.head()

<class 'pandas.DataFrame'>
Index: 711 entries, 0 to 731
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Text       711 non-null    str
 1   Sentiment  711 non-null    str
 2   Timestamp  711 non-null    datetime64[us]
 3   User       711 non-null    str
 4   Platform   711 non-null    str
 5   Hashtags   711 non-null    str
 6   Retweets   711 non-null    int64
 7   Likes      711 non-null    int64
 8   Country    711 non-null    str
 9   Year       711 non-null    int64
 10  Month      711 non-null    int64
 11  Day        711 non-null    int64
 12  Hour       711 non-null    int64
dtypes: datetime64[us](1), int64(6), str(6)
memory usage: 77.8 KB

,Text,Sentiment,Timestamp,User,Platform,Hashtags,Retweets,Likes,Country,Year,Month,Day,Hour
0,enjoying a beautiful day at the park!,Positive,2023-01-15 12:30:00,User123,Twitter,#Nature #Park,15,30,USA,2023,1,15,12
1,traffic was terrible this morning.,Negative,2023-01-15 08:45:00,CommuterX,Twitter,#Traffic #Morning,5,10,Canada,2023,1,15,8
2,just finished an amazing workout! 💪,Positive,2023-01-15 15:45:00,FitnessFan,Instagram,#Fitness #Workout,20,40,USA,2023,1,15,15
3,excited about the upcoming weekend getaway!,Positive,2023-01-15 18:20:00,AdventureX,Facebook,#Travel #Adventure,8,15,UK,2023,1,15,18
4,trying out a new recipe for dinner tonight.,Neutral,2023-01-15 19:55:00,ChefCook,Instagram,#Cooking #Food,12,25,Australia,2023,1,15,19

#### Saving Cleaned Data

In [61]:
df.to_csv("cleaned_sentiment_data.csv", index=False, sep=',')
print("Cleaned dataset!")

Cleaned dataset!

## Summary

- Loaded and explored the sentiment dataset  
- Removed unnecessary columns to reduce noise  
- Cleaned text data by standardizing format and removing extra characters  
- Checked and handled missing values  
- Removed duplicate records to maintain data integrity  
- Standardized categorical data for consistency  
- Converted data types to appropriate formats  
- Validated the cleaned dataset  
- Saved the final dataset  

- The dataset is now cleaned and structured